module.exports = [
    require('./app/webpack.config.js'),
    require('./app/webpack.main.config.js'),
    require('./tabby-core/webpack.config.js'),
    require('./tabby-electron/webpack.config.js'),
    require('./tabby-web/webpack.config.js'),
    require('./tabby-settings/webpack.config.js'),
    require('./tabby-terminal/webpack.config.js'),
    require('./tabby-local/webpack.config.js'),
    require('./tabby-community-color-schemes/webpack.config.js'),
    require('./tabby-plugin-manager/webpack.config.js'),
    require('./tabby-ssh/webpack.config.js'),
    require('./tabby-serial/webpack.config.js'),
    require('./tabby-web/webpack.config.js'),
    require('./web/webpack.config.js'),
]
