export { Tab } from './tab'
export { TabRecoveryProvider } from './tabRecovery'
export { ToolbarButtonProvider, IToolbarButton } from './toolbarButtonProvider'
export { ConfigProvider } from './configProvider'
export { HotkeyProvider, IHotkeyDescription } from './hotkeyProvider'
export { DefaultTabProvider } from './defaultTabProvider'

export { AppService } from 'services/app'
export { ConfigService } from 'services/config'
export { PluginsService } from 'services/plugins'
export { ElectronService } from 'services/electron'
export { HotkeysService } from 'services/hotkeys'
