name: tabby
version: '1.0.0'
summary: A terminal for a modern age
description: |
  Tabby is a local, SSH and serial terminal heavily inspired by Hyper.

grade: devel
confinement: devmode

apps:
  tabby:
    command: opt/tabby/tabby

parts:
  app:
    plugin: nodejs
    source: .
    build-packages:
      - libfontconfig-dev
    override-build: |
      yarn
      ./scripts/build-native.js
      yarn run build
      ./scripts/build-linux.js
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/tabby || true
      cp -ar dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/opt/tabby/
