name: Windows prebuilds (Electron 37)

on:
  workflow_dispatch:        # allow "Run workflow" button
  push:
    branches: [ master, main ]

env:
  ELECTRON_VERSION: 37.3.1
  NODE_VERSION: 22.20.0      # satisfies node-abi >= 4.9
  CI: true
  SENTRYCLI_SKIP_DOWNLOAD: 1
  npm_config_msvs_version: "2022"
  GYP_MSVS_VERSION: "2022"

jobs:
  prebuilds-x64:
    runs-on: windows-latest

    steps:
      - name: Checkout (full history + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add upstream & fetch Eugeny tags
        shell: bash
        run: |
          git remote add upstream https://github.com/Eugeny/tabby.git || true
          git fetch upstream --tags --prune
          # ensure local tag namespace filled (fork + upstream)
          git fetch --tags --force
          git describe --tags || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Enable Yarn 1.x via Corepack
        shell: bash
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate

      - name: Cache Yarn v1
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\Yarn\Cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        shell: bash
        run: yarn --network-timeout 300000

      - name: Build native modules for Electron
        shell: bash
        run: node scripts/build-native.mjs

      - name: Upload prebuilt .node artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-prebuilds-electron-${{ env.ELECTRON_VERSION }}-x64
          if-no-files-found: error
          path: |
            app/node_modules/**/build/Release/*.node

  installer-x64:
    needs: prebuilds-x64
    runs-on: windows-latest

    steps:
      - name: Checkout (full history + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add upstream & fetch Eugeny tags
        shell: bash
        run: |
          git remote add upstream https://github.com/Eugeny/tabby.git || true
          git fetch upstream --tags --prune
          git fetch --tags --force
          git describe --tags || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Enable Yarn 1.x via Corepack
        shell: bash
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate

      - name: Install deps
        shell: bash
        run: yarn --network-timeout 300000

      - name: Prepackage plugins
        shell: bash
        run: node scripts/prepackage-plugins.mjs

      - name: Build Windows installer
        shell: bash
        run: node scripts/build-windows.mjs

      - name: Upload installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer-electron-${{ env.ELECTRON_VERSION }}-x64
          path: |
            dist/**/*.{exe,zip,nupkg,blockmap,msi}
